# Generated by Django 4.1.13 on 2024-08-07 19:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Name', models.CharField(max_length=50, null=True, unique=True)),
                ('isVehicleManufacturer', models.BooleanField(default=False)),
                ('isProductManufacturer', models.BooleanField(default=False)),
                ('Logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductBrands',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('Name', models.CharField(max_length=50, null=True, unique=True)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('Logo', models.URLField()),
                ('Manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='part_admin.manufacturer')),
            ],
        ),
    ]
