# Generated by Django 5.0.6 on 2024-07-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.ManyToManyField(blank=True, to='parts.carousel'),
        ),
    ]
