# Generated by Django 4.1.13 on 2024-09-14 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_group',
            name='choice_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parts.choice'),
        ),
    ]
