# Generated by Django 5.1.1 on 2024-09-13 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '__first__'),
        ('parts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Costtypes',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost_category', models.CharField(choices=[('Product', 'Product'), ('Nonproduct', 'Nonproduct'), ('Tax', 'Tax'), ('Discount', 'Discount')], max_length=255)),
                ('is_order_level_cost', models.BooleanField()),
                ('is_order_item_level_cost', models.BooleanField()),
                ('transaction_type', models.CharField(choices=[('D', 'D'), ('C', 'C')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderitems',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.product')),
            ],
        ),
        migrations.CreateModel(
            name='orderitemcost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('currency_code', models.CharField(max_length=255)),
                ('cost_type', models.ForeignKey(limit_choices_to={'is_order_item_level_cost': True}, on_delete=django.db.models.deletion.CASCADE, to='parts.costtypes')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.orderitems')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderon', models.DateTimeField(auto_now_add=True)),
                ('orderstatus', models.CharField(choices=[('New', 'New'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=255)),
                ('orderedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.orders'),
        ),
        migrations.CreateModel(
            name='ordercosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('currency_code', models.CharField(max_length=255)),
                ('cost_type', models.ForeignKey(limit_choices_to={'is_order_item_level_cost': False}, on_delete=django.db.models.deletion.CASCADE, to='parts.costtypes')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.orders')),
            ],
        ),

        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_alert_threshold', models.IntegerField(default=0)),
                ('back_order_threshold', models.IntegerField(default=0)),
                ('reorder_threshold', models.IntegerField(default=0)),
                ('instock_count', models.IntegerField(default=0)),
                ('reversed_count', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.product')),
            ],
        ),
        migrations.CreateModel(
            name='Productsummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.product')),
                ('Tags', models.ManyToManyField(to='parts.tags')),
            ],
        ),
    ]
