# Generated by Django 5.0.6 on 2024-06-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parts_fits',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='parts_litre',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='parts_no',
            field=models.CharField(max_length=255),
        ),
    ]
