# Generated by Django 4.1.13 on 2024-09-19 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.product'),
            preserve_default=False,
        ),
    ]
