# Generated by Django 4.1.13 on 2024-09-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_alter_choice_group_choice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice_group',
            name='choice_name',
        ),
    ]
