# Generated by Django 5.0.6 on 2024-06-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_product_parts_fits_alter_product_parts_litre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='parts_conditions',
            new_name='parts_condition',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='parts_warrenty',
            new_name='parts_warranty',
        ),
    ]
