# Generated by Django 5.0.6 on 2024-06-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.URLField()),
                ('carousel_code', models.CharField(max_length=255)),
                ('carousel_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.brand')),
                ('carousel_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.category')),
            ],
        ),
    ]
