# Generated by Django 5.0.6 on 2024-06-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_rename_parts_conditions_product_parts_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parts_offer',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='parts_warranty',
            field=models.IntegerField(max_length=2),
        ),
    ]
