# Generated by Django 4.1.13 on 2024-08-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_product_product_fit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_fit',
        ),
    ]
