# Generated by Django 5.0.6 on 2024-06-20 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_alter_brand_brand_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='carousel_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.product'),
            preserve_default=False,
        ),
    ]
