# Generated by Django 4.1.13 on 2024-09-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0004_choice_group_choice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice_group',
            name='choice_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choice_name', to='parts.choice'),
        ),
    ]
