# Generated by Django 4.1.13 on 2024-09-14 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_alter_choice_group_choice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice_group',
            name='group_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice_group',
            name='choice_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.choice_name'),
        ),
    ]
