# Generated by Django 4.1.13 on 2024-08-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_remove_product_product_fit'),
        ('parts', '0005_remove_relatedproduct_related_product2_and_more'),
    ]

    operations = [
    ]
