# Generated by Django 5.0.6 on 2024-06-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_carousel_carousel_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_offer',
            field=models.IntegerField(default=0),
        ),
    ]
