# Generated by Django 5.0.6 on 2024-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0005_alter_product_parts_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='this_parts_fits',
        ),
        migrations.AddField(
            model_name='product',
            name='this_parts_fits',
            field=models.ManyToManyField(to='parts.vehicle'),
        ),
    ]
