# Generated by Django 4.1.13 on 2024-09-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_choice_group_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice_group',
            name='choice_name',
        ),
    ]
