# Generated by Django 5.0.6 on 2024-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_remove_product_this_parts_fits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parts_price',
            field=models.IntegerField(default=0),
        ),
    ]
