# Generated by Django 4.1.13 on 2024-08-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
