# Generated by Django 4.1.13 on 2024-09-21 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0007_uservehicle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVehicle',
        ),
    ]
