# Generated by Django 4.1.13 on 2024-09-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_remove_choice_name_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice_group',
            name='choice_name',
        ),
        migrations.AddField(
            model_name='choice_group',
            name='choice_name',
            field=models.ManyToManyField(to='parts.choice_name'),
        ),
    ]
