# Generated by Django 5.0.6 on 2024-06-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0008_alter_product_parts_litre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parts_offer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='parts_warranty',
            field=models.IntegerField(),
        ),
    ]
