# Generated by Django 4.1.13 on 2024-09-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0009_remove_choice_group_choice_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSellerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_place', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='sellergroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.addsellergroup'),
        ),
    ]
