# Generated by Django 4.1.13 on 2024-09-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_addsellergroup_alter_sellergroup_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellergroup',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AddSellerGroup',
        ),
    ]
