# Generated by Django 4.1.13 on 2024-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0011_alter_sellergroup_group_delete_addsellergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.CharField(default=1, max_length=1023),
            preserve_default=False,
        ),
    ]
