# Generated by Django 4.1.13 on 2024-09-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0012_seller_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parts.sellergroup'),
            preserve_default=False,
        ),
    ]
