# Generated by Django 4.1.13 on 2024-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0013_seller_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='gst_number',
            new_name='tin',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='use_the_address_for_next_time',
            new_name='use_the_billing_address',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='contact',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
