# Generated by Django 4.1.13 on 2024-09-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0015_remove_shippingaddress_use_the_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='use_the_billing_address',
        ),
    ]
