# Generated by Django 4.1.13 on 2024-09-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0017_rename_vehicle_category_vehicle_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
