# Generated by Django 4.1.13 on 2024-09-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0019_remove_feedback_email_delete_dbillingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
