# Generated by Django 4.1.13 on 2024-09-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0022_carts_delete_dbillingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
