# Generated by Django 4.1.13 on 2024-09-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0023_alter_orderitems_id_delete_dbillingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
