# Generated by Django 4.1.13 on 2024-09-17 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0024_orders_session_key_delete_dbillingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orderedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
