# Generated by Django 4.1.13 on 2024-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0025_alter_orders_orderedby_delete_dbillingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='costtypes',
            name='percentage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
