# Generated by Django 4.1.13 on 2024-09-18 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0027_preferences_remove_product_cost_effective_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='selecter_seller',
            new_name='selected_seller',
        ),
    ]
