# Generated by Django 4.1.13 on 2024-09-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0028_rename_selecter_seller_preferences_selected_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='contact',
        )
    ]
